name: Build and Deploy CLaSH Catalog

# this action triggers automatically when changes are pushed
on:
  push:
    branches:
      - main
    paths:
      - 'data/datasets.yaml' #new or updated data entries
      - 'build.py' #changes to the build script
      - 'templates/**' #chandes to the HTML templates and style
      - '.github/workflows/deploy.yml' #changes to this file
  workflow_dispatch: # allows manual triggering of the workflow


# permissions
permissions:
  contents: read # allows the workflow to read the repository contents
  pages: write # allows the workflow to publish to GitHub Pages
  id-token: write # allows the workflow to authenticate with GitHub's OIDC provider

#concurrency control
concurrency:
  group: 'pages' 
  cancel-in-progress: true # cancels any in-progress workflow runs in the same group when a new run is triggered

#jobs 
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest # specifies the runner environment

        environment:
            name: github-pages # sets the environment name to github-pages
            url: ${{ steps.deployment.outputs.page_url }} # sets the environment URL to the deployed GitHub Pages URL
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4 # checks out the repository code
    
        - name: Set up Python
          uses: actions/setup-python@v5 # sets up a Python environment
          with:
              python-version: '3.11' 
      
        - name: Setup Pages
          uses: actions/configure-pages@v4 # configures the GitHub Pages environment
    
        - name: Install dependencies # installs the necessary Python packages for the build script
          run: |
            python -m pip install --upgrade pip
            pip install pyyaml jinja2 
    
        - name: Build static site # runs the build script to generate HTML pages
          run: |
            python build.py 
    
        - name: Upload Pages Artifact
          uses: actions/upload-pages-artifact@v4 # uploads the generated HTML pages as an artifact
          with:
            path: ./site #must match the output directory specified in build.py

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4 # deploys the generated HTML pages to GitHub Pages
       